CREATE DATABASE RRHH
DROP DATABASE RRHH
USE RRHH

CREATE TABLE EMPLEADO(
ID_EMPLEADO INT IDENTITY,
CODIGO_EMPLEADO VARCHAR(50),
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
TELÉFONO VARCHAR(50),
ID_DEPARTAMENTO INT,
ID_CARGO INT,
FECHA_INGRESO DATE,
SALARIO DECIMAL,
ESTATUS VARCHAR(50),
CONSTRAINT PK_CE PRIMARY KEY (ID_EMPLEADO),
CONSTRAINT FK_IDD1 FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
CONSTRAINT FK_IDCA1 FOREIGN KEY(ID_CARGO) REFERENCES CARGO(ID_CARGO)
)

CREATE TABLE DEPARTAMENTO(
ID_DEPARTAMENTO INT IDENTITY,
NOMBRE VARCHAR(50),
CODIGO_DEPARTAMENTO VARCHAR(50),
CONSTRAINT PK_IDD PRIMARY KEY (ID_DEPARTAMENTO)
)

CREATE TABLE CARGO(
ID_CARGO INT IDENTITY,
CARGO VARCHAR(50),
CONSTRAINT PK_IDCA PRIMARY KEY (ID_CARGO)
)

CREATE TABLE NOMINA(
ID_NOMINA INT IDENTITY,
ID_EMPLEADO INT,
ANIO INT,
MES INT,
MONTO_TOTAL DECIMAL,
CONSTRAINT PK_IDNO PRIMARY KEY (ID_NOMINA),
CONSTRAINT FK_CE5 FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
)

DROP TABLE NOMINA

CREATE TABLE SALIDA_EMPLEADO(
ID_SALIDA_EMPLEADO INT IDENTITY,
ID_EMPLEADO INT,			     
TIPO_SALIDA VARCHAR(50),		 
MOTIVO VARCHAR(200),
FECHA_SALIDA DATE,
CONSTRAINT PK_IDSE PRIMARY KEY(ID_SALIDA_EMPLEADO),
CONSTRAINT FK_CE1 FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
)

CREATE TABLE VACACIONES(
ID_VACACIONES INT IDENTITY,
ID_EMPLEADO INT,
DESDE DATE,             
HASTA DATE, 			   
CORRESPONDIENTE VARCHAR(100),   
COMENTARIO VARCHAR(200), 
CONSTRAINT PK_IDV PRIMARY KEY (ID_VACACIONES),
CONSTRAINT FK_CE2 FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
)

CREATE TABLE PERMISO(
ID_PERMISO INT IDENTITY,
ID_EMPLEADO INT,
DESDE DATE,             
HASTA DATE,          
COMENTARIOS VARCHAR(200),
CONSTRAINT PK_IDP PRIMARY KEY (ID_PERMISO),
CONSTRAINT FK_CE3 FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
)

CREATE TABLE LICENCIA(
ID_LICECIA INT IDENTITY,
ID_EMPLEADO INT,
DESDE DATE,           
HASTA DATE,            
MOTIVO VARCHAR(100),
COMENTARIOS VARCHAR(200),
CONSTRAINT PK_IDL PRIMARY KEY (ID_LICECIA),
CONSTRAINT FK_CE4 FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
)